### ISSUE TITLE
Changelog seems outdated

### ISSUE THREAD

**Issue by olia-bn** [xyNNN/GoogleTagManagerBundle#45]
The changelog for this package seems out of date.

Last version listed is 2.3.0 (2017-08-22)

**Comment by xyNNN** [comment]
Thanks @olia-bn - You're right. The CHANGELOG.md itself is obsolete, because we track changes about the releases/tags of GitHub. See https://github.com/xyNNN/GoogleTagManagerBundle/releases for changes above version 2.3.0

If you want you can make a pull request to delete the CHANGELOG.md from the repository. If not, I will delete it.

**Comment by xyNNN** [comment]
See https://github.com/xyNNN/GoogleTagManagerBundle/commit/082b5855578db697b29844c96ea8379365c2835b
